---
title: 'Hruday: '
author: "Hruday"
format: 
  html: 
    #### IMPORTANT ###
    self-contained: true ## Creates a single HTML file as output
    code-fold: show ## Code folding; allows you to show/hide code chunks
    #### USEFUL ###
    code-tools: true ## Includes a menu to show/hide all chunks
    #### OPTIONAL ###
    code-line-numbers: true ## Line numbers in code chunks
    df-print: paged ## Sets how dataframes are automatically printed
    theme: lux ## Controls the font, colours, etc.
    table-of-contents: true ## (Useful) Creates a table of contents!
    number-sections: true ## (Optional) Puts numbers next to heading/subheadings
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)  
library(plotly)  
library(DT)  
library(limma)  
library(clusterProfiler)  
library(org.Hs.eg.db)  
library(enrichplot)  
library(WGCNA)
```

```{r}
exprs_mat <- read.csv("../../datasets/kidney_data/exprs_mat.csv",row.names=1)
outcome_data <- read.csv("../../datasets/kidney_data/outcome_mat.csv")
exprs_mat
outcome_data
```